version: 2.1

orbs:
  docker_orb: circleci/docker@2.0.3

workflows:
  workflows:
    jobs:
      - docker_orb/publish:
          executor:
            name: docker_orb/machine
            dlc: true
          lint-dockerfile: true
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
