version: 2.1

orbs:
  docker_orb: circleci/docker@2.0.3
  heroku_orb: circleci/heroku@1.2.6

jobs:
  build:
    executor:
      name: docker_orb/machine
      dlc: true
    steps:
      - checkout
      - docker_orb/build:
          lint-dockerfile: true
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: latest
      - run:
          command: |
            docker tag $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME \
              registry.heroku.com/$CIRCLE_PROJECT_REPONAME/web
      - docker_orb/push:
          image: registry.heroku.com/$CIRCLE_PROJECT_REPONAME/web
      - heroku_orb/release-docker-image:
          app-name: $CIRCLE_PROJECT_REPONAME
