version: 2.1

orbs:
  docker_orb: circleci/docker@2.0.3
  heroku_orb: circleci/heroku@1.2.6

jobs:
  build:
    executor:
      name: docker_orb/machine
      dlc: true
    steps:
      - checkout
      - docker_orb/hadolint
      - heroku_orb/push-docker-image:
          app-name: $CIRCLE_PROJECT_REPONAME
          process-types: web
      - heroku_orb/release-docker-image:
          app-name: $CIRCLE_PROJECT_REPONAME
